client_app/routes/journeys.py
import math

from flask import Blueprint, jsonify

from flask import flash, render_template, request, redirect, url_for
import requests
from flask_paginate import Pagination, get_page_parameter
from client_app import API_BASE_URL

journey_bp = Blueprint('journey', __name__)

page_data = {'journeys': None}


@journey_bp.route('/journeys/')
def home():
    page = request.args.get('page', 1, type=int)
    print(f"Requesting page {page} on journeys home page")
    response = requests.get(f'{API_BASE_URL}journeys/{page}')
    journeys = response.json()
    page_data['journeys'] = journeys

    # get total journey
    response = requests.get(f'{API_BASE_URL}journeys/total')
    total_journeys = response.json()['total_journeys']
    print(f"Total journey are {total_journeys}")
    per_page = 15
    total_pages = math.ceil(total_journeys / per_page)  # Calculate the total pages

    page_data['start_page'] = 1 if ((page // 20) * 20) == 0 else ((page // 20) * 20)
    page_data['end_page'] = page_data['start_page'] + 20

    pagination = Pagination(page=page, total=total_journeys, per_page=per_page, bs_version=4)
    return render_template("journeys.html", page_data=page_data, pagination=pagination, total_pages=total_pages)


@journey_bp.route('/journey/<int:journey_id>')
def journey_details(journey_id):
    page_data = {}
    print(f"getting details of journey {journey_id}")
    response = requests.get(f'{API_BASE_URL}journey/{journey_id}')
    journey = response.json()
    page_data['journey'] = journey
    return render_template('journey_details.html', page_data=page_data)


@journey_bp.route('/journey/add', methods=['POST', 'GET'])
def add_journey():
    """
     Adds journey  information from API endpoint and renders it on add_journey.html
     """
    if request.method == 'GET':
        # get list of journey so that user can select from them
        # Get the existing journey from the API for keys to make form dynamic
        journey = requests.get(f'{API_BASE_URL}journey/{20}', timeout=20).json()
        print("Rendering Add form for journeys")
        return render_template('add_journey.html', journey=journey, page_data=page_data)

    elif request.method == 'POST':
        print(f"inserting new journey {request.form}")
        journey = {}
        user_inputs = ''
        try:
            for key, user_inputs in request.form.items():
                if key == 'covered_distance_m':
                    journey[key] = int(user_inputs)
                elif key == 'departure_station_id':
                    journey[key] = int(user_inputs)
                elif key == 'return_station_id':
                    journey[key] = int(user_inputs)
                else:
                    journey[key] = user_inputs
        except ValueError:
            flash(f'Enter Valid Numbers {user_inputs}', 'danger')
            return redirect(url_for('journey.add_journey'))
        # Send a PUT request to update the journey in the API
        response = requests.post(f'{API_BASE_URL}journeys/1', json=journey, timeout=20)
        if response.status_code == 201:
            print("journey added successfully")
            # if the edit is successful go to the journey details page
            flash('journey added successfully', 'success')
            return redirect(url_for('journey.home'))
        # Error updating journey
        flash(f'Error! adding journey. {response.status_code}|{response.text}', 'danger')
        return redirect(url_for('journey.add_journey'))
        return redirect(url_for('journey.add_journey'))


@journey_bp.route('/journey/getjourneylist', methods=['GET'])
def get_journey_list():
    search_query = request.args.get('search', '')
    print(f"Searching for {search_query}")
    # Perform the necessary logic to retrieve journey suggestions based on the search query

    # Assuming you have a list of journey objects
    response = requests.get(f'{API_BASE_URL}journey/search/{search_query}')
    journeys = response.json()
    print(journeys)

    # Filter the journeys based on the search query
    filtered_journeys = [journey for journey in journeys if search_query.lower() in journey["name"].lower()]

    # Return the filtered journeys as a JSON response
    return jsonify(filtered_journeys)

client_app/routes/stations.py
import math

from flask import Blueprint, jsonify

from flask import flash, render_template, request, redirect, url_for
import requests
from flask_paginate import Pagination, get_page_parameter
from client_app import API_BASE_URL

station_bp = Blueprint('station', __name__)

page_data = {'stations': None}



@station_bp.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    print(f"Requesting page {page} on stations home page")
    response = requests.get(f'{API_BASE_URL}stations/{page}')
    stations = response.json()
    page_data['stations'] = stations

    #get total stations
    response = requests.get(f'{API_BASE_URL}stations/total')
    total_stations = response.json()['total_stations']
    per_page = 15
    total_pages = math.ceil(total_stations / per_page)  # Calculate the total pages
    pagination = Pagination(page=page, total=total_stations, per_page=per_page, bs_version=4)
    return render_template("stations.html", page_data=page_data, pagination=pagination, total_pages=total_pages)


@station_bp.route('/station/<int:station_id>')
def station_details(station_id):
    page_data = {}
    print(f"getting details of station {station_id}")
    response = requests.get(f'{API_BASE_URL}station/{station_id}')
    station = response.json()
    page_data['station'] = station
    return render_template('station_details.html', page_data=page_data)


@station_bp.route('/station/add', methods=['POST', 'GET'])
def add_station():
    """
     Adds station  information from API endpoint and renders it on add_station.html
     """
    if request.method == 'GET':
        # Get the existing station from the API for keys to make form dynamic
        station = requests.get(f'{API_BASE_URL}station/{20}', timeout=20).json()
        print("Rendering Add form for stations")
        return render_template('add_station.html', station=station, page_data=page_data)

    elif request.method == 'POST':

        station = {}
        user_inputs = ''
        # looping through form to make it dynamic
        try:
            for key, user_inputs in request.form.items():
                if key == 'kapasiteet':
                    station[key] = int(user_inputs)
                elif key == 'x':
                    station[key] = float(user_inputs)
                elif key == 'y':
                    station[key] = float(user_inputs)
                else:
                    station[key] = user_inputs
        except ValueError:
            flash(f'Enter Valid Numbers {user_inputs}', 'danger')
            return redirect(url_for('station.add_station'))
        # Send a PUT request to update the station in the API
        response = requests.post(f'{API_BASE_URL}stations/1', json=station, timeout=20)
        if response.status_code == 201:
            print("station added successfully")
            # if the edit is successful go to the station details page
            flash('station added successfully', 'success')
            return redirect(url_for('station.home'))
        # Error updating station
        flash(f'Error! adding station. {response.status_code}', 'danger')
        return redirect(url_for('station.add_station'))

@station_bp.route('/station/<int:station_id>/delete', methods=['POST'])
def delete_station(station_id):
    """
     Deletes station record from API endpoint and navigates to home.html to render stations records on home.html

     """
    response = requests.delete(f'{API_BASE_URL}station/{station_id}')
    if response.status_code == 204:
        return redirect(url_for('station.home'))
    return f'Error: {response.status_code}', response.status_code


@station_bp.route('/station/getstationlist', methods=['GET'])
def get_station_list():
    search_query = request.args.get('search', '')
    print(f"Searching for {search_query}")
    # Perform the necessary logic to retrieve station suggestions based on the search query

    # Assuming you have a list of station objects
    response = requests.get(f'{API_BASE_URL}station/search/{search_query}')
    stations = response.json()
    print(stations)

    # Filter the stations based on the search query
    filtered_stations = [station for station in stations if search_query.lower() in station["name"].lower()]

    # Return the filtered stations as a JSON response
    return jsonify(filtered_stations)

client_app/templates/add_journey.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Journey</h1>
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <form id="searchForm">
        <div class="input-group">
          <input type="text" id="departureSearchInput" name="departure_station" class="form-control" placeholder="Select departure station...">
          <input type="hidden" id="departureStationInput" name="departure_station_id">
        </div>
      </form>
      <div id="departureSuggestionBox"></div>
    </div>
    <div class="col">
      <form id="returnSearchForm">
        <div class="input-group">
          <input type="text" id="returnSearchInput" name="return_station" class="form-control" placeholder="Select return station...">
          <input type="hidden" id="returnStationInput" name="return_station_id">
        </div>
      </form>
      <div id="returnSuggestionBox"></div>
    </div>
  </div>
</div>

    <form method="POST" action="{{ url_for('journey.add_journey') }}">
        <div class="form-group">
            <label for="departure_t">From Date:</label>
            <input type="text" name="departure_t" id="departure_t" class="form-control" autocomplete="off">
        </div>
        <div class="form-group">
            <label for="return_t">To Date:</label>
            <input type="text" name="return_t" id="return_t" class="form-control" autocomplete="off">
        </div>
          <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script>
    flatpickr("#departure_t, #return_t", {
      enableTime: true,
      enableSeconds: true,
      dateFormat: "Y-m-d H:i:S",
    });
  </script>
        <div class="form-group">
            <label for="covered_distance">Covered Distance in Meters:</label>
            <input type="text" name="covered_distance_m" id="covered_distance" class="form-control">
        </div>
        <input type="hidden" id="departure_station" name="departure_station_id" value="">
        <input type="hidden" id="return_station" name="return_station_id" value="">
        <button type="submit" class="btn btn-primary">Add</button>
    </form>

    <a href="{{ url_for('journey.add_journey') }}" onclick="return confirm('Are you sure you want to cancel this journey?')">Cancel</a>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/smoothness/jquery-ui.css">

    <script>
              var jq = $.noConflict();
        jq(function() {
            const departureSearchForm = document.getElementById("departureSearchForm");
            const departureSearchInput = document.getElementById("departureSearchInput");
            const departureSuggestionBox = document.getElementById("departureSuggestionBox");
            const departureStationInput = document.getElementById("departure_station");

            const returnSearchForm = document.getElementById("returnSearchForm");
            const returnSearchInput = document.getElementById("returnSearchInput");
            const returnSuggestionBox = document.getElementById("returnSuggestionBox");
            const returnStationInput = document.getElementById("return_station");

            departureSearchInput.addEventListener("input", function(event) {
                const searchQuery = event.target.value;
                if (searchQuery.length > 3) {                    fetch(`/station/getstationlist?search=${encodeURIComponent(searchQuery)}`)
                        .then((response) => response.json())
                        .then((data) => {
                            departureSuggestionBox.innerHTML = "";
                            data.forEach((station) => {
                                const suggestion = document.createElement("p");
                                const link = document.createElement("a");
                                link.textContent = station.name;
                                link.href = "#";
                                suggestion.appendChild(link);
                                suggestion.addEventListener("click", function() {
                                    departureSearchInput.value = station.name; // Set the value of search input to the clicked suggestion
                                    departureStationInput.value = station.id; // Set the value of the hidden input for departure station
                                    departureSuggestionBox.innerHTML = ""; // Clear the suggestion box after selecting a suggestion
                                });
                                departureSuggestionBox.appendChild(suggestion);
                            });
                        });
                } else {
                    departureSuggestionBox.innerHTML = ""; // Clear the suggestion box if search query length is not sufficient
                }
            });

            returnSearchInput.addEventListener("input", function(event) {
                const searchQuery = event.target.value;
                if (searchQuery.length > 3) {
                    fetch(`/station/getstationlist?search=${encodeURIComponent(searchQuery)}`)
                        .then((response) => response.json())
                        .then((data) => {
                            returnSuggestionBox.innerHTML = "";
                            data.forEach((station) => {
                                const suggestion = document.createElement("p");
                                const link = document.createElement("a");
                                link.textContent = station.name;
                                link.href = "#";
                                suggestion.appendChild(link);
                                suggestion.addEventListener("click", function() {
                                    returnSearchInput.value = station.name; // Set the value of search input to the clicked suggestion
                                    returnStationInput.value = station.id; // Set the value of the hidden input for return station
                                    returnSuggestionBox.innerHTML = ""; // Clear the suggestion box after selecting a suggestion
                                });
                                returnSuggestionBox.appendChild(suggestion);
                            });
                        });
                } else {
                    returnSuggestionBox.innerHTML = ""; // Clear the suggestion box if search query length is not sufficient
                }
            });
        });
    </script>
{% endblock %}

client_app/templates/add_station.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Station</h1>
<form method="POST" action="{{ url_for('station.add_station') }}">
    {% for key, value in station.items() %}
        {% if key != 'id' and key != 'total_departure_journeys' and key != 'total_return_journeys' %}
            <div class="form-group">
                <label for="{{ key }}">{{ key|title }}</label>
                <input type="text" class="form-control" id="{{ key }}" name="{{ key }}" value="{{Nothing}}">
            </div>
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Add</button>
</form>

    <a href="{{ url_for('station.add_station') }}" onclick="return confirm('Are you sure you want to cancel this station?')">Cancel</a>
{% endblock %}

client_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}City Bike App{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <style>
        body {
            padding-top: 5rem;
            margin-bottom: 60px; /* This pushes the content up to make room for the footer */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Stations</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mx-auto justify-content-center">

                <li class="nav-item">
                    <a class="nav-link text-white px-3" href="/journeys/">Journeys</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white px-3" href="/journey/add">Add Journey</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white px-3" href="/station/add">Add Station</a>
                </li>
            </ul>

        </div>
    </nav>

   <div class="container">
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
      {% if category == 'success' %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% elif category == 'danger' %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% elif category == 'info' %}
                        <div class="alert alert-info" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% block content %}{% endblock %}
</div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

client_app/templates/journeys.html
{% extends 'base.html' %}

{% block content %}
<h3>Journeys ({{pagination.total}})</h3>
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <form id="searchForm">
        <div class="input-group">
          <input type="text" id="searchInput" name="search" class="form-control" placeholder="Search By Departure Station...">
        </div>
      </form>
      <div id="suggestionBox"></div>
    </div>
  </div>
</div>

<script src="{{ url_for('static', filename='journey_search.js') }}"></script>

<div class="journeys-container">
  {% for journey in page_data.journeys %}
      <p class="journey-text">
      Departure Station: <a href="{{ url_for('station.station_details', station_id=journey.departure_station_id) }}">{{ journey.departure_station_name }}</a>
      Return Station: <a href="{{ url_for('station.station_details', station_id=journey.return_station_id) }}">{{ journey.return_station_name }}</a>
      Distance Traveled: {{ journey.covered_distance_m | int / 1000 }}Km ({{ journey.covered_distance_m}}m)
      Duration: {{ journey.duration_sec | int // 60 }} Minutes {{ journey.duration_sec }}(s)</a>
      </p>
  {% endfor %}
</div>


<div class="pagination justify-content-center flex-wrap">
    {% if pagination.has_prev %}
        {% set prev_page_num = pagination.page - 1 %}
        <a class="btn btn-primary mr-2 mb-2" href="{{ url_for('journey.home', page=prev_page_num) }}">Previous</a>
    {% endif %}

    {% for page_num in range(page_data.start_page, page_data.end_page + 1) %}
        {% if page_num == pagination.page %}
            <a class="btn btn-primary active mr-2 mb-2" href="{{ url_for('journey.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-primary mr-2 mb-2" href="{{ url_for('journey.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% endfor %}

    {% if pagination.has_next %}
        {% set next_page_num = pagination.page + 1 %}
        <a class="btn btn-primary mb-2" href="{{ url_for('journey.home', page=next_page_num) }}">Next</a>
    {% endif %}
</div>


{% endblock %}

{% block custom_styles %}
  <style>
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 0.5rem;
    }

    .card-text {
      margin-bottom: 0.25rem;
    }

    .card-text:last-child {
      margin-bottom: 0;
    }
  </style>

{% endblock %}

client_app/templates/station_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{page_data.station.Name}} Details</h1>
        <hr>
        <div class="row">

            <div class="col-md-6">
                <table class="table table-bordered table-hover">
                    <tbody>
                      {% for key, value in page_data.station.items() %}
                        <tr>
                            <td><strong>{{key}}</strong></td>
                            <td>{{ value }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
               <div class="button-row" style="display: flex; justify-content: space-between;">
    <form id="deleteForm" action="{{ url_for('station.delete_station', station_id=page_data.station.id) }}" method="post">
        <button type="submit" class="btn btn-danger" onclick="return confirmDelete()">Delete Station</button>
    </form>
</div>

<script>
    function confirmDelete() {
        return confirm('Are you sure you want to delete this station?');
    }
</script>

            </div>

        </div>
    </div>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

client_app/templates/stations.html
{% extends 'base.html' %}

{% block content %}
<h3>Stations ({{pagination.total}})</h3>
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <form id="searchForm">
        <div class="input-group">
          <input type="text" id="searchInput" name="search" class="form-control" placeholder="Search...">
        </div>
      </form>
      <div id="suggestionBox"></div>
    </div>
  </div>
</div>
<script src="{{ url_for('static', filename='station_search.js') }}"></script>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for station in page_data.stations %}
      <div class="col">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title">{{ station.name }}</h5>
            <p class="card-text">Address: {{ station.adress }}</p>
            <p class="card-text">Operator: {{ station.operaattor }}</p>
            <p class="card-text">Capacity: {{ station.kapasiteet }}</p>
            <p class="card-text"><a href="https://www.google.com/maps/search/?api=1&query={{ station.y }},{{ station.x }}" target="_blank">Pin Location</a></p>
            <a href="{{ url_for('station.station_details', station_id=station.id) }}" class="btn btn-primary">Details</a>

          </div>
        </div>
      </div>
    {% endfor %}
  </div>

<div class="pagination justify-content-center flex-wrap">
    {% if pagination.has_prev %}
        {% set prev_page_num = pagination.page - 1 %}
        <a class="btn btn-primary mr-2 mb-2" href="{{ url_for('station.home', page=prev_page_num) }}">Previous</a>
    {% endif %}

    {% for page_num in range(1, total_pages + 1) %}
        {% if page_num == pagination.page %}
            <a class="btn btn-primary active mr-2 mb-2" href="{{ url_for('station.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-primary mr-2 mb-2" href="{{ url_for('station.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% endfor %}

    {% if pagination.has_next %}
        {% set next_page_num = pagination.page + 1 %}
        <a class="btn btn-primary mb-2" href="{{ url_for('station.home', page=next_page_num) }}">Next</a>
    {% endif %}
</div>




{% endblock %}

{% block custom_styles %}
  <style>
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 0.5rem;
    }

    .card-text {
      margin-bottom: 0.25rem;
    }

    .card-text:last-child {
      margin-bottom: 0;
    }
  </style>

{% endblock %}